# Generated by Django 4.2.4 on 2023-09-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='asd', to='core.department'),
        ),
    ]
