# Generated by Django 4.2.4 on 2023-08-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='file',
            name='core_file_name_02f7a3_idx',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='core_projec_deadlin_d84ad7_idx',
        ),
        migrations.AddField(
            model_name='queuelogic',
            name='permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['name', 'file'], name='core_file_name_f268e4_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['deadline', 'number'], name='core_projec_deadlin_c3ad60_idx'),
        ),
    ]
