# Generated by Django 4.2.5 on 2023-09-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
