# Generated by Django 4.2.5 on 2023-09-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='order_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
