# Generated by Django 4.2.7 on 2023-11-09 19:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuelogic',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
