# Generated by Django 4.2.4 on 2023-08-26 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_queuelogic_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queuelogic',
            name='project',
        ),
    ]
