# Generated by Django 4.2.4 on 2023-09-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_file_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='files', to='core.department'),
        ),
    ]
