# Generated by Django 4.2.5 on 2023-09-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='destiny',
            field=models.CharField(choices=[('Production', 'Production'), ('Secretariat', 'Secretariat')], max_length=30),
        ),
    ]
