# Generated by Django 4.2.4 on 2023-08-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_queuelogic_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='department',
            field=models.ManyToManyField(blank=True, to='core.department'),
        ),
    ]
