# Generated by Django 4.2.4 on 2023-08-22 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_file_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='department',
        ),
    ]
