# Generated by Django 4.2.7 on 2023-11-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_queuelogic_paused_date_queuelogic_planned_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuelogic',
            name='test',
            field=models.BooleanField(default=False),
        ),
    ]
