# Generated by Django 4.2.4 on 2023-08-27 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_queuelogic_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queuelogic',
            options={'ordering': ['department__order']},
        ),
    ]
