# Generated by Django 4.2.4 on 2023-08-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_project_core_projec_deadlin_d84ad7_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='file',
            name='core_file_name_02f7a3_idx',
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['name', 'file'], name='core_file_name_f268e4_idx'),
        ),
    ]
