# Generated by Django 4.2.7 on 2023-11-11 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_queuelogic_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuelogic',
            name='real_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queuelogic',
            name='real_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
