# Generated by Django 4.2.4 on 2023-08-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_queuelogic_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['order']},
        ),
        migrations.RemoveIndex(
            model_name='file',
            name='core_file_name_f268e4_idx',
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['name'], name='core_file_name_02f7a3_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['file'], name='core_file_file_4d9480_idx'),
        ),
    ]
