# Generated by Django 4.2.7 on 2023-11-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_user_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.CharField(choices=[('Autokomplet', 'Autokomplet'), ('AKR', 'Akr')], default='Autokomplet', max_length=12),
            preserve_default=False,
        ),
    ]
