# Generated by Django 4.2.7 on 2023-11-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('Busy', 'Busy'), ('Free', 'Free')], max_length=255, null=True),
        ),
    ]
