# Generated by Django 4.2.7 on 2023-11-12 15:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuelogic',
            name='users',
            field=models.ManyToManyField(related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
