# Generated by Django 4.2.7 on 2023-11-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_queuelogic_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('Busy', 'Busy'), ('Free', 'Free')], default='Free', max_length=5),
        ),
    ]
